homePage: /

overview: /DBR-Basic-Info/overview/

userGuide: /DBR-Basic-Info/user-guide/
userGuide_windows: /DBR-Basic-Info/user-guide/windows/
userGuide_linux: /DBR-Basic-Info/user-guide/linux/
userGuide_iOS: /DBR-Basic-Info/user-guide/iOS/
userGuide_android: /DBR-Basic-Info/user-guide/Android/
userGuide_wasm: /DBR-Basic-Info/user-guide/wasm/

evaluationTools: /DBR-Basic-Info/evaluation-tools/

securityIssues: /DBR-Basic-Info/security-issues/  

manual: /DBR-Detailed-Info/manual/

demosSamples: /DBR-Detailed-Info/samples-and-demos/

intermediateResults: /DBR-Enhancements/intermediate-results/

dpm: /DBR-Enhancements/dpm/

panoramaOverlap: /DBR-Enhancements/panorama-and-overlap/

3dReconstruction: /DBR-Enhancements/3d-reconstruction/

pdfVectors: /DBR-Enhancements/pdf-vectors/  

industrialSolutions: /DBR-Extend-Info/industrial-solutions/

parameterUsage: /DBR-Extend-Info/how-to-use-parameters/

complicateImageHandling: /DBR-Extend-Info/how-to-handle-complicate-images/

licenseUsageTracking: /DBR-Extend-Info/license-and-usage-tracking/

barcodeBasisKnowledge]: /DBR-Extend-Info/barcode-basis-knowledge/

imageProcessingKnowledge: /DBR-Extend-Info/image-processing-knowledge/ 
